# Data Parameters
data:
  cadenza_data_root: /media/gerardoroadabike/Extreme SSD1/Challenges/CAD3/CLIP/dataset
  dataset: cadenza_data
  sample_rate: 44100  # Sample rate of the audio files

split: valid  # Dataset split to use (train, valid, test)

# Parameters for computing STOI
compute:
  stoi_sample_rate: 10000   # Sample rate for STOI computation
  batch: 1
  n_batches: 1

separator:
  keep_vocals: False # Set to True if you want to keep the separated vocals
  sample_rate: 44100 # sample_rate of the separation model

# Hydra parameters
hydra:
  run:
    dir: exp
  job:
    chdir: True
