path:
  root: /media/gerardoroadabike/Extreme SSD1/Challenges/CAD2/cadenza_data/cad2/task1
  metadata_dir: ${path.root}/metadata
  music_dir: ${path.root}/audio
  musics_file: ${path.metadata_dir}/music.valid.json
  alphas_file: ${path.metadata_dir}/alpha.json
  listeners_file: ${path.metadata_dir}/listeners.valid.json
  scenes_file: ${path.metadata_dir}/scene.valid.json
  scene_listeners_file: ${path.metadata_dir}/scene_listeners.valid.json
  exp_folder: ./exp_${separator.causality} # folder to store enhanced signals and final results

input_sample_rate: 44100   # sample rate of the input mixture
remix_sample_rate: 32000  # sample rate for the output remixed signal
HAAQI_sample_rate: 24000  # sample rate for computing HAAQI score

separator:
  causality: causal
  device: ~
  separation:
    number_sources: 2
    segment: 6.0
    overlap: 0.1
    sample_rate: ${input_sample_rate}


ha: # hearing aid
  compressor:
    crossover_frequencies: [353.55, 707.11, 1414.21, 2828.43, 5656.85] # [250, 500, 1000, 2000, 4000] * sqrt(2)
    sample_rate: ${input_sample_rate}
  camfit_gain_table:
    noisegate_levels: 40
    noisegate_slope: 0
    cr_level: 0
    max_output_level: 100

evaluate:
  whisper_version: base.en
  set_random_seed: True
  small_test: True
  batch_size: 1  # Number of batches
  batch: 0       # Batch number to evaluate

soft_clip: False

# hydra config
hydra:
  run:
    dir: ${path.exp_folder}
  job:
    chdir: True