# Zenodo download path: path to the zenodo download folder.
# root: root path of the dataset. This path will contain the audio and metadata folders
path:
  zenodo_download_path: /media/gerardoroadabike/Extreme SSD1/Challenges/CAD2/Rebalancing_Classical/Zenodo
  root: /media/gerardoroadabike/Extreme SSD1/Challenges/CAD2/cadenza_data/cad2/task2
  metadata_dir: ${path.root}/metadata
  music_dir: ${path.root}/audio

input_sample_rate: 44100
remix_sample_rate: 32000


# hydra config
hydra:
  job:
    chdir: True