name: whisper
system: whisper.est_vocals
mode: vocals # Separate vocals from the mixture using a source separation model then run ASR
whisper_version: base.en
contractions_file: "../contractions.csv"
batch: 1
n_batches: 1

separator:
  keep_vocals: False # Set to True if you want to keep the separated vocals
  sample_rate: 44100 # sample_rate of the separation model

reference: processed
