data:
  cadenza_data_root: /media/gerardoroadabike/Extreme SSD1/Challenges/CAD3/CLIP/dataset
  dataset: cadenza_data
  sample_rate: 44100  # Sample rate of the audio files

precomputations: ../precomputed

# Hydra parameters
hydra:
  run:
    dir: exp
  job:
    chdir: True